#define E2BIG 1 ///ARGUMENT LIST TOO LONG
#define EFBIG 2 ///FILE TOO LARGE
#define ENOENT 3 ///NO SUCH FILE OR DIRECTORY
#define ENAMETOOLONG 4 ///FILENAME TOO LONG
#define EEOF 5 ///REACHED END OF FILE
#define EFTF 6 ///FILE TABLE FULL
#define EUDWV 7 ///UNDEFINED WHENCE VALUE
#define EINVPERM 8 ///INVALID DATE OR PERMISSIONS
#define EPROCESSDOESNOTEXIST 9 //PROCESS DOES NOT EXIST

extern int errno;